# Generated by Django 3.1.4 on 2022-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220501_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='photo',
            field=models.ImageField(upload_to='auctions/pics'),
        ),
    ]
