# Generated by Django 3.1.4 on 2022-05-01 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20220501_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='photo',
            field=models.ImageField(upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
