# Generated by Django 3.1.4 on 2022-05-01 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20220501_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='current_price',
        ),
    ]
