# Generated by Django 3.1.4 on 2022-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
