# Generated by Django 3.1.4 on 2022-06-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20220613_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='last_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
